# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  enable:
    - errcheck      # Checks for unchecked errors
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled words
    - gocritic      # Provides diagnostics for bugs, performance and style
    - gosec         # Security-focused linter
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
