# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: 2

linters:
  enable:
    - errcheck      # Checks for unchecked errors
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled words
    - gocritic      # Provides diagnostics for bugs, performance and style
    - gosec         # Security-focused linter
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters

linters-settings:
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G301  # Directory permissions
      - G304  # File path variable
      - G306  # File permissions

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Exclude logger from error checking (intentional design - print statements)
    - path: internal/logger/logger\.go
      linters:
        - errcheck
    # Exclude config file permissions warnings (0755 and 0644 are fine for config)
    - path: internal/config/config\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - .github
    - .idea
