# GoReleaser configuration for gcloud-switcher
# See: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - id: gcloud-switcher
    main: ./cmd/gcloud-switcher
    binary: gcloud-switcher
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      # Skip ARM builds for Windows
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: gcloud-switcher-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

# Release notes template
release:
  github:
    owner: xgourmandin
    name: gcloud-switch
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## GCloud Switcher {{ .Version }}
    
    Release Date: {{ .Date }}
    
    ### Installation
    
    #### Homebrew (macOS/Linux)
    ```bash
    brew install xgourmandin/tap/gcloud-switcher
    ```
    
    #### Scoop (Windows)
    ```powershell
    scoop bucket add xgourmandin https://github.com/xgourmandin/scoop-bucket
    scoop install gcloud-switcher
    ```
    
    #### Go Install
    ```bash
    go install github.com/xgourmandin/gcloud-switch/cmd/gcloud-switcher@{{ .Version }}
    ```
    
    #### Manual Download
    Download the appropriate binary for your platform from the assets below.
  footer: |
    **Full Changelog**: https://github.com/xgourmandin/gcloud-switch/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ---
    
    ### Shell Completion
    
    After installation, set up shell completion:
    ```bash
    # Bash
    gcloud-switcher completion bash | sudo tee /etc/bash_completion.d/gcloud-switcher
    
    # Zsh
    gcloud-switcher completion zsh > "${fpath[1]}/_gcloud-switcher"
    
    # Fish
    gcloud-switcher completion fish > ~/.config/fish/completions/gcloud-switcher.fish
    ```
    
    See [COMPLETION.md](https://github.com/xgourmandin/gcloud-switch/blob/main/COMPLETION.md) for detailed setup instructions.
